# Generated by Django 5.2.8 on 2025-12-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsusers",
            name="email",
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
    ]
