# Generated by Django 5.2.8 on 2025-12-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_newsusers_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsusers",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsusers",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
