# Generated by Django 5.2.8 on 2025-12-19 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_message_is_read_newsusers_is_online_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsusers",
            name="last_seen",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
