# Generated by Django 6.0 on 2025-12-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_newsusers_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsusers",
            name="verify_code",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
