# Generated by Django 6.0 on 2026-01-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_newsusers_verify_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsusers",
            name="verify_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
