# Generated by Django 6.0 on 2026-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_newsusers_verify_code_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsusers",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
