# Generated by Django 6.0 on 2026-01-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_newsusers_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_for",
            field=models.JSONField(default=list),
        ),
    ]
