# Generated by Django 6.0 on 2026-01-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_message_deleted_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_for_everyone",
            field=models.BooleanField(default=False),
        ),
    ]
