# Generated by Django 6.0 on 2026-01-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_message_is_unsend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_unsend",
        ),
    ]
