# Generated by Django 6.0 on 2026-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_message_deleted_for_everyone"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_profile",
            field=models.JSONField(default=list),
        ),
    ]
