# Generated by Django 6.0 on 2026-01-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_message_deleted_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsusers",
            name="blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsusers",
            name="failed_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
