# Generated by Django 6.0 on 2026-01-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_newsusers_blocked_until_newsusers_failed_attempts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsusers",
            name="verify_code",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
