# Generated by Django 6.0 on 2026-01-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_newsusers_verify_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsusers",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
