# Generated by Django 6.0 on 2026-02-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_newsusers_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsusers",
            name="api_token",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
