# Generated by Django 6.0 on 2026-02-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_newsusers_api_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsusers",
            name="api_token",
        ),
    ]
