# Generated by Django 6.0 on 2026-03-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_newsusers_api_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsusers",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.png",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
