# Generated by Django 6.0 on 2026-03-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_newsusers_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsusers",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="https://res.cloudinary.com/douy6goys/image/upload/v1690000000/default.png",
                null=True,
                upload_to="",
            ),
        ),
    ]
