# Generated by Django 6.0 on 2026-03-08 16:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_newsusers_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsusers",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                default="https://res.cloudinary.com/douy6goys/image/upload/v1690000000/default_vcxic3.png",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
