# Generated by Django 6.0 on 2026-03-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_newsusers_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("az", models.CharField(max_length=255)),
                ("tr", models.CharField(max_length=255)),
                ("en", models.CharField(max_length=255)),
                ("ru", models.CharField(max_length=255)),
            ],
        ),
    ]
